# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - seekin

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://meseekin.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_4bb4a037d2874c30b76f3a1acaabffae }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a8b889c999e44c7483cdd2458d85e4bf }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: meseekin.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4bb4a037d2874c30b76f3a1acaabffae }}/seeking_image:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'seekin'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_731e1bead7de4f9b8a7bdca621a961ac }}
        images: 'meseekin.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4bb4a037d2874c30b76f3a1acaabffae }}/seeking_image:${{ github.sha }}'